### ISSUE TITLE
I mentioned the merger, but it was a mistake.

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#13]
I mentioned the merger, but There is always a warning
"All checks have failed .1 failing check"
I don't know if you can see it.
I'm sorry, I'm not very good with github.
There may have been duplicate buggy commits.

branch name: 1.0.6.0_W_ACDC-Switch-LaptopComputer
Realization of laptop battery AC power automatic switching power plan
Please review
Based on “CTRL +F1” version
Documentation based on feature additions modifications
Code should be better to observe separation
Thanks for your hard work!

**Comment by SebastianBecker2** [comment]
Git and GitHub are very complex and hard to understand. Don't worry. It takes time to learn it but it's worth it.

The Pull Request (PR) you created was a bit confusing. There seem to have been source files copied from the project folder into the solution folder. The Pull Request showed them as new files. It took me a bit to understand what happened. But I still don't understand why that happened. Maybe you copied them accidentally in your local Working Copy. Make sure when you commit a changes in your local Repository that you check exactly what changes you made. And make sure that a single commit contains only changes for a single feature. For example, one of your commits for the battery had a change in background color of a dialog. Ideally this would be two separate commits. One for everything regarding the battery and another commit for the background color. It's okay if a commit is just a single line of code that changed.

About the checks that failed in the Pull Request. There are basically two checks right now. One is the check if the merge causes any conflicts. This happened because I made changes in the main branch and pushed them to GitHub. While you made changes in the same files, but you didn't have my new changes yet. This can happen. You can either pull the changes from my GitHub Repository into your Fork and solve those conflicts there. Or you can solve the conflicts in the Pull Request.
The other check that is done is a build test. I set up an automatic build on AppVeyor for every commit that gets pushed or Pull Request that is made. This way, it's easy to see if the code compiles properly. Often the code compiles perfectly on computer but doesn't on AppVeyor. It just makes sure that everything is build properly when someone else tries to build the code.

I have checked your Pull Request. But the first thing that confused me was that it was based on your "CTRL + F1" version. At this point, I don't want to implement the "CTRL + F1" version since I think the new implementation for hotkeys is better. You have to update your Fork to get those changes. Though I'm not 100% done yet. So I haven't made a new release. If you think there are problems with my implementation and I should revert those and take your "CTRL + F1" version, you have to tell me why. Keep in mind that I'm still implementing the hotkey to cycle through the Power Schemes. So this will probably be finished in the next few days. It will allow the user to individually specify the hotkey to cycle through the Power Schemes. And an option to specify if it should cycle through all Power Schemes or only to those that are selected as visible.

If you want to keep your current changes of the "CTRL + F1" version until I'm finished with my changes, you can create a new branch that is based of my current Main branch. This way you can make the Battery Manager changes and merge them into your branch with the "CTRL + F1" version and create a Pull Request to push them into my main branch. Without having any conflicts between the two different hotkey implementations.
This sounds pretty complex and it surely is at first. But if you did it once and understand it, it becomes easy to use.

As for the Battery Manager. I'm not 100% sure what the best way is to implement this. From what I understand, in Windows you don't have separate Power Schemes for Battery or AC. Instead every Power Scheme has different settings on how to behave when the computer is running n Battery or AC. My understanding is, if you have a Power Scheme for energy saving, you can tell windows how this Power Scheme is supposed to behave when on AC and how it's supposed to behave when it's on Battery.
But having the option to switch to a specific Power Scheme when on Battery might still be interesting for certain situations. I just don't know how it should interact with the Power Rules the user can set up. Right now, the Power Rules are pretty simple. They only have an order. The first Power Rule that triggers determines the Power Scheme that will be activated. Maybe the Battery Management can just be implemented as a Power Rule. So the user can create a new Power Rule. And a Power Rule can either be based on a process or on the Battery Manager.
Either way, if you think the Battery Manager is a good idea, I'm looking forward to implementing your solution. I might have to make a few changes. For example, I try to avoid using WinAPI calls directly and instead use Vanara library. But I can easily change the WinAPI calles to Vanara calls myself. So don't worry about that.

I'm sorry this is so much text. I hope it's understandable. I don't know how well google translation works for English to Chinese.
Thank you for your contributions and interest in this project. It motivates me to do work more on this.

**Comment by wuguo138428** [comment]
1. I've been using the functions provided by github html
but I don't know what tool would be more appropriate to use 

2.ACDC has some levels of  
DC(Battery) > power plan on start > AC 
to make sure the AC power on start “power plan on start” does not fail
DC on start to make sure expect the most power saving option

I've now added the functionality to the “rules” interface to make this happen
Locked and non-repeatable additions.

3. The above fulfills the basic functionality, as I see that the power plan is partially functional.
From here on down, a better preliminary idea.

**Comment by wuguo138428** [comment]
进一步为每个程序设置 电池 交流电选项

**Comment by wuguo138428** [comment]
![Uploading 屏幕截图 2024-05-22 004633.png…]()

**Comment by wuguo138428** [comment]
![屏幕截图 2024-05-22 004633](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/d94a31aa-e529-4469-ac90-7775be6e8048)

**Comment by wuguo138428** [comment]
My ability is limited, so I've fixed ctrl + F1 for the time being. 
So if the author has a better way, I won't participate in the shortcut switching design, and concentrate on the ACDC design.
But I have a design idea to suggest

"And an option to specify if it should cycle through all Power Schemes or only to those that are selected as visible.”

Here just customize the shortcut, visible traversal plus a few fixed power plan switching can meet all the needs,
Benefit: Simple design/logic, easy to implement.
Example: 
ctrl + f1 is used to traverse the visible loop.
ctrl + f2 to switch to customized fixed power plan “1”.
ctrl + f2 to switch to customized fixed power plan “2”.
ctrl + f....... and many more customizable keys, etc.

**Comment by SebastianBecker2** [comment]
I'm starting to understand how you want to implement this.

I just pushed my latest changes regarding the hotkeys. This now allows the user to set a hotkey to cycle through the Power Schemes. I reworked the SettingsDlg quite a bit.
When you merge those changes into your repository, you will certainly get a lot of conflicts. I hope you can get it to work without losing your changes for the Battery implementation.

Don't worry so much about your changes in the SettingsDlg. If the buttons aren't at the right spot or don't properly move when resizing the window, it's not a big deal. I can clean that up later.
The important part is that the implementation works and is understandable. Try to avoid comments in Chinese. I can use google translate for those but I might not be able to understand what you mean.

If you have an implementation that does what you want, create a Pull Request for it. I can give you feedback there and we can talk about it. It doesn't have to be perfect. The most important thing is that the code is understandable.

BTW: I will upload a new preview of 1.0.8 which includes the current implementation of the hotkeys.
You will see that you can easily define any hotkey combination you like for what you want.

**Comment by SebastianBecker2** [comment]
Here the new preview version:
https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.0.8.0-(hotkey)

I really hope you can set up your hotkeys exactly the way you like.

**Comment by wuguo138428** [comment]
There's one more thing I forgot to mention.
Need an animated interface in the center of the screen to let the user know which power source to switch to.
also need to add a switch to make this animated screen visible or not.
Because some laptop drivers come with this animation

**Comment by SebastianBecker2** [comment]
Created a new release that includes a toast notification:
https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.1.0.0
