### ISSUE TITLE
The settings window is now too much content and too big

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#15]
The settings window is now too much content and too big
Causes the smaller laptop screen to be incomplete
Confirmation buttons are covered, etc.
1. It should be organized and categorized in tabbed mode
Different function items in the same tab
2. Add a slider to turn pages

**Comment by SebastianBecker2** [comment]
I merged both PRs and did some refactoring of the code.
I tried to keep the functionality as it was implemented.
Though I changed the way the user selects the Power Scheme for Batter Power or AC Power. It's two combo boxes now. Similar to how the initial Power Scheme is selected. This makes it simpler to get the selected Power Schemes without having to cache them.

I hope I didn't screw anything up. The new pre-release for that is here:
https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.0.9.0-(refactor)

Could you check if everything still works the way you want it too and give me some feedback?

**Comment by SebastianBecker2** [comment]
Forgot to mention. The changes I made are in the branch https://github.com/SebastianBecker2/PowerPlanSwitcher/tree/Refactoring

**Comment by SebastianBecker2** [comment]
Had a bug in there that would cause an exception. After changing the BatteryMonitor to return a PowerSchemeGuid instead of setting it itself, it would return an empty Guid if it didn't intent to change the PowerScheme. I forgot to check for it. So it happened that the baselinePowerSchemeGuid would be set to an empty Guid. This shouldn't have happened.
Fixed it now. It's not in the setup obviously. But it's pushed to the branch Refactoring.
