### ISSUE TITLE
How about adding a customized cycle and list

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#17]
How about adding a customized cycle and list, “Cycle only through visible Power Plans” and “Cycle through all existing Power Plans “ could be left out，Then create a fourth new tab to put the loop shortcut in the newly created tab , but I don't know if that's necessary either!

**Comment by SebastianBecker2** [comment]
I'm not sure what you mean with "customized cycle and list". Can you give a little more detail?

**Comment by wuguo138428** [comment]
You can define your own power options for the cycle.
Repeatable additions
Sequence can be changed
Just like “Rules”.
![屏幕截图 2024-05-27 161303](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/068ce686-2242-401a-8db3-3e91f77bb269)

**Comment by SebastianBecker2** [comment]
I'm not sure it's a good idea because it makes the settings more complicated. And the use-case would be very limited. I don't think many users would have a significant amount of Power Schemes to cycle through.
But on the other hand, I was concerned about the order when cycling. Right now it's based on the order the Power Schemes are returned when calling the WinAPI functions for that. But as far as I know, there is no guarantee that this order is even consistent in any way.

I will think about it. I want to keep the settings dialog easy, so that new users don't get deterred and overwhelmed.

**Comment by wuguo138428** [comment]
![屏幕截图 2024-05-29 034148](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/494837a3-8de6-4e1e-8c5b-7a1fc8171f60)
I have another plan.
Upload pictures later

**Comment by SebastianBecker2** [comment]
I was thinking about this a lot. And I can't really see a benefit in this change. To me, it seems like it just makes the SettingsDlg a lot more complicated.

That is mostly because I can't really find a good reason why someone would have enough different Power Schemes to warrant the creation of an additional list.
I personally have only two Power Schemes. Power Saving and Balance. Which are both default Power Schemes. I get that someone might have three or even four. But even with four, it shouldn't be an issue to quickly cycle through them to get the user wants.

Maybe I just can't see the use case of having many different Power Schemes.
