### ISSUE TITLE
The "Battery Management" function does not save the settings properly.

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#21]

**Comment by SebastianBecker2** [comment]
I'm not sure what you mean with "Battery Management" function.
The only function that should save any settings should be the SettingsDlg::HandleBtnOkClick(...).
I had a few issues with combo boxes being empty when there was no system battery (not a laptop).
But that resulted in a crash and should be fixed in v1.1.0.0.

**Comment by wuguo138428** [comment]
![屏幕截图 2024-06-26 152640](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/3ee6e04d-b64c-4df3-8f37-6bae481b4f30)
Functions as shown
does not save and take effect properly
Reopening the settings after saving will restore the settings as shown in the picture

**Comment by wuguo138428** [comment]
“SettingsDlg.cs”in line 71 to 99 is bug
There is a problem with the save read, Resulting in features not being implemented

**Comment by SebastianBecker2** [comment]
I fixed the problem with the PowerScheme selection for AC and Battery.
New release is here: https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.2.0.0
