### ISSUE TITLE
malposition

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#3]
![屏幕截图 2024-05-11 003540](https://github.com/SebastianBecker2/PowerPlanSwitcher/assets/106533733/b432c054-4ddd-4f8e-982a-4211b9738e6e)

**Comment by SebastianBecker2** [comment]
I tried to reproduce it. But I couldn't. I checked everything and this problem shouldn't happen. But since I created a new version anyways, I just reworked the dialog a bit. I just hope it didn't get worse.
If you have any issues with the new version, please tell me. But I hope its fixed for you now.

You can get the new version 1.0.5.0 here: https://github.com/SebastianBecker2/PowerPlanSwitcher/releases
Just install the new version. It replaces the old one.
