### ISSUE TITLE
‘SettingsDlg’ lines 67-68 repeat for “CmbInitialPowerScheme”.

### ISSUE THREAD

**Issue by wuguo138428** [SebastianBecker2/PowerPlanSwitcher#32]
‘SettingsDlg’ lines 67-68 repeat for “CmbInitialPowerScheme”.
I did a git push via ‘vs’, but I don't know if it works.
![屏幕截图 2024-07-30 100156](https://github.com/user-attachments/assets/ff680a76-ca0c-4530-a668-5d6838ded148)

**Comment by SebastianBecker2** [comment]
I'm not sure if you're up to date with the current main.
Line 67-68 of SettingsDlg.cs are:
`  var index = CmbColorTheme.Items.IndexOf(Settings.Default.ColorTheme);`
`  if (index != -1 && index < CmbColorTheme.Items.Count)`
I checked it right here on github. You might need to pull changes from the remote.

**Comment by wuguo138428** [comment]
I made a mistake. It should be lines 38 to 42.

**Comment by SebastianBecker2** [comment]
Okay, I see now.
Yeah, seems like I forgot to remove the previous code when I refactored. I will fix it.
Be warned: I'm in the process of finishing up a rework for the AC / PowerLine handling. Instead of configuring those directly, they will be a type of rule the user can create. Though I'm not done yet. I need to finish up some tests.

**Comment by SebastianBecker2** [comment]
Released version 1.2.1.0: https://github.com/SebastianBecker2/PowerPlanSwitcher/releases/tag/v1.2.1.0
The issue should be fixed in that version.
