### ISSUE TITLE
Why does it install itself in the Windows/Installer folder?

### ISSUE THREAD

**Issue by unalignedcoder** [SebastianBecker2/PowerPlanSwitcher#35]
Like the title says.
Just wondering if this was an error or a requirement of some kind.

**Comment by SebastianBecker2** [comment]
I'm not sure what you mean with "Windows/Installer folder"?
The default path to install should be %programfiles%\PowerPlanSwitcher.
I can't think of many situation where this would be different.

Can you elaborate?

**Comment by unalignedcoder** [comment]
I have uninstalled it now, but the installer had placed it in a "C:\Windows\Installer\<someID>" folder.
It's possible it happened because of a problem on my end.
Anyway the program runs just fine in portable mode so that's what I'm doing now.

**Comment by SebastianBecker2** [comment]
I don't even have a single folder in C:\Windows that starts with "Installer". I'm really not sure why it would install it there.
But as long as it works now, it's fine.
If you have any further problems, just create a new issue.

**Comment by unalignedcoder** [comment]
Just to clarify, I meant "C:\Windows\Installer\<some-id>
You certainly have the "Installer" folder in that location (may be hidden in your explorer), and a series of subfolders in it with IDs as names.

**Comment by SebastianBecker2** [comment]
You're right. I had the option to hide protected system files active.
It seems like the folders inside usually have icons for installed apps.
Maybe just some meta information for show the app in the list of installed apps.
The weird part is, for PowerPlanSwitcher, it has the whole executable in there. Though it's called "ProductIcon.exe". I'm not sure that is 100% correct.
I would assume it has to do with the way I put my icons in the app.
I will take a look.

**Comment by SebastianBecker2** [comment]
Okay, I found the issue. The windows\installer folder is used by MSI installers (possibly others too) to store relevant files. Like icons to show in the list of installed apps or files to perform a repair on the installation.

I changed it to use the actual icon file instead of the executable.
But the installer should have put the actual executable PowerPlanSwitcher.exe in the program files folder. And add start menu entries and a auto-start entry for it.

I haven't released a new setup yet. I don't think it's necessary. Your stuff works. The ProductIcon.exe is not a problem in itself. MSI explicitly allows either ico files or exe files to be used as a reference for the icon. Though it might not be a smart idea to use the executable, it's not a real problem.

Installing a new version replaces the ProductIcon.exe with the new ProductIcon.ico file. By the magic of MSI.

Here more details if you're interested:
The reason for the ProductIcon.exe there was that I used the executable as a reference to the icon when creating the installer. The name ProductIcon.exe was given by me. (It's basically more than 10 years old and copied from an example I found on the internet.)
I expected it to extract the icon from the executable. But instead it just takes the executable as THE file for the icon. Hence it stores it in windows\installer.
Btw: I tried running the ProductIcon.exe. But it seems to be blocked. Probably due to it's location. Not sure.

**Comment by unalignedcoder** [comment]
> I haven't released a new setup yet. I don't think it's necessary.

If the shortcut in the start menu points to Producticon,exe in the Windows\Installer folder (as it did in my case), the whole app is ran from there. I don't think it should be doing that.

**Comment by SebastianBecker2** [comment]
I just double and triple checked. I don't think it's the case that the start menu shortcut or auto start shortcut starts the executable that is in Windows\Installer.

The wxs file clearly shows that the shortcuts belongs to the ProductComponent and is marked as advertised.
The ProductComponent is the PowerPlanSwitcher.exe in the platform specific ProgramFiles folder with the PowerPlanSwitcher as the subfolder.
Afaik I couldn't even directly reference the ProductIcon.exe that is in Windows\Installer.

I double checked the resulting MSI file with Orca. The shortcuts reference the ProductComponent and from there on out the actual executable in the proper path.

I also checked on 4 machines. Two existing ones and two clean VMs I set up. One VM is Win11, the rest is Win10.
It's not possible to directly check the target of the shortcuts since they are marked as advertised. When checking the properties of the shortcut, it shows "PowerPlanSwitcher" as the target. Nor does it short the path it's executed in.
But I verified by checking the image path of the executable that is started when I use the shortcut.
On all machines it shows the image path to be C:\Program Files\PowerPlanSwitcher\PowerPlanSwitcher.exe.

And I tried to inspect the ProductIcon.exe.
Keep in mind that the files name is just defined by the ID of the Icon element in the MSI file.
It turns out, the ProductIcon.exe isn't the actual executable of the project. But instead the DLL that is created along side the executable. Before the setup is created, the executable and all necessary binaries are combined into a single executable. I thought $(var.PowerPlanSwitcher.TargetPath) would refer to the actual executable. But when checking out the size, content and headers of the executables, I noticed that the content differ severely. But the PowerPlanSwitcher.dll has the exact content of the ProductIcon.exe in Windows\Installer.
So I doubt there is anything directly executable there anyways. It's a DLL file that has .exe at the end of the filename.
